name: mi primer workflow

on:
  push:

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Ejecutar main.py
        run: python main.py
